apiVersion: v1
kind: Service
metadata:
  name: svc3
spec:
  type: NodePort
  selector:
    app: app1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31080 # Cổng mà pod đó expose ra thuộc dải 30000-32767