apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
spec:
  maxReplicas: 7
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
